### ISSUE TITLE
WebHook and Other Formatting Issues

### ISSUE THREAD

**Issue by Sade66** [Eufranio/MagiBridge#21] opened 2017-07-20 02:59 UTC
- [x] WebHooks have the same prefix issues as before.
![image](https://user-images.githubusercontent.com/19366945/28398501-7808a342-6cd5-11e7-886c-182a3a97047f.png)

- [ ] Usernames and prefixes are still coming through the ``%message%`` modifier.
![image](https://user-images.githubusercontent.com/19366945/28398531-95d6daba-6cd5-11e7-993d-94b754e86268.png)

- [x] It would be nice to have a ``%toprole%`` modifier for the Minecraft to Discord formats (Including the WebHooks layout). That way we can differentiate our Minecraft prefix layouts from the Discord one.

**Comment by Eufranio** [comment] 2017-07-20 09:57
Please dont open duplicated issues, the old one still open so you can comment there. The %toprole% placeholder from Discord to Server is planned already, and is covered by %prefix% in the Server to Discord format (depending on your permission plugin, the %prefix% placeholder will have the highest prefix of the player's rank).

**Comment by Sade66** [comment] 2017-07-20 12:13
Sorry, I forgot to close the other one.

_Sent from my Motorola XT1585 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Sade66** [comment] 2017-07-20 12:15
The problem with the %prefix% modifier is that is includes the while prefix, and not just the name of the role. We want to be able to make the Discord prefixes appear different than the Minecraft ones, which is where the %toprole% would come in handy.

_Sent from my Motorola XT1585 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Eufranio** [comment] 2017-07-20 12:23
So, you mean **%topgroup%** instead %toprole%, since roles are from Discord.

**Comment by Sade66** [comment] 2017-07-20 12:30
Yes

_Sent from my Motorola XT1585 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Eufranio** [comment] 2017-07-20 21:00
Usernames and prefix coming from the **%message%** placeholder is due to Boop, disable it and you're fine. I've sent a message to the Boop dev and am waiting for a fix.

@Sade66, could you please test [this version](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.8.1-all.jar), without Boop, please?

**Comment by Sade66** [comment] 2017-07-20 21:09
@Eufranio We don't have Boop installed, and it's disabled in the config. Any other ideas?

_Sent from my Motorola XT1585 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fcpwiz** [comment] 2017-07-20 21:13
@Sade66 Should we try downloading the one he sent and keep Boop disabled?

**Comment by Sade66** [comment] 2017-07-20 21:14
@fcpwiz We can, but it's hard to disable what you don't have. 😁

_Sent from my Motorola XT1585 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Eufranio** [comment] 2017-07-20 21:17
I've tried a clean setup and it's working here, with Nucleus + MagiBridge + LuckPerms. The issue is that some other plugin is handling the chat formatting and replacing the message body with the whole message line. 

If you find out which plugin (from your setup) is messing up with the chat, let me know and I can try to make MagiBridge compatible with it. You can test with your plugin set on a local server and see if the issue occurrs there. There's not much I can do, sorry!

**Comment by Sade66** [comment] 2017-07-20 21:19
Hmm.. We use Nucleus for custom rank-based chat formats and that's the only chat plugin we have. 

I'll update and see if it's fixed.

We're you able to fix the webhook formatting?

_Sent from my Motorola XT1585 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Eufranio** [comment] 2017-07-20 21:20
None of your current issues is happening here, so everything should be fixed.

**Comment by Sade66** [comment] 2017-07-21 02:05
Great work! The only issue we're still having is the one with the prefixes.

**Comment by Eufranio** [comment] 2017-07-22 13:46
Make a copy of your plugins and their config on a local server, and test removing one by one until you find which one is causing the issue, so I can take a look on it.

**Comment by Eufranio** [comment] 2017-07-22 16:35
It was a typo on my end, please test with [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.8.1-all.jar).

**Closed** 2017-07-22 16:35 UTC
Labels: bug
