### ISSUE TITLE
Sometimes channel topic message is not updating

### ISSUE THREAD

**Issue by Wadimich** [Eufranio/MagiBridge#38] opened 2017-08-03 12:50 UTC
Issue is on screenshot.
![screenshot](https://user-images.githubusercontent.com/21156193/28922563-1d2c9d7a-7874-11e7-91f8-1aa164292d8e.png)
It seems, that all channels have "freezed topics". I didn't tried to reload, but i think, it will work, or not.

**Comment by Eufranio** [comment] 2017-08-03 18:00
Please send a fml-server-latest of when the issue is happening with you, I can't reproduce this...

**Comment by Wadimich** [comment] 2017-08-03 18:06
[fml-server-latest.zip](https://github.com/Eufranio/MagiBridge/files/1198160/fml-server-latest.zip)
This is full log from one of servers, where issue still exists.

**Comment by Eufranio** [comment] 2017-08-03 18:09
Hmmm, looks like MagiBridge won't restart the Topic Updater when there is a network problem, even if it was already fixed.

**Comment by Eufranio** [comment] 2017-08-03 18:24
@Wadimich it should be fixed in [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.9.1-all.jar).

**Closed by Eufranio** 2017-08-03 18:24 UTC
Labels: bug
