### ISSUE TITLE
Older Version Support. 

### ISSUE THREAD

**Issue by itsbennji** [Eufranio/MagiBridge#210] opened 2021-01-14 04:31 UTC
spongeforge-1.10.2-2477-5.2.0-BETA-2793 <--- version support for this plugin would be greatly appreciated, for older skyfactory servers. Support for this plugin would be nice too. "Nucleus-0.27.0-S5.1-plugin.jar". Thank you!

**Comment by Eufranio** [comment] 2021-04-07 19:36
Duplicate of #192.

**Closed as completed by Eufranio** 2021-04-07 19:36 UTC
